version: '3.2'

services:

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#develop
    command: python3 ./runserver.py
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 5555:5555

  tiles:
    build:
      context: https://github.com/accessmap/accessmap-vt.git
    command: yarn app 0.0.0.0
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DOCKER=no
    volumes:
      - ./config/tiles/sources.json:/www/sources.json
    ports:
      - 3001:3001

  webapp:
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#feature/analytics
    # Note: binding 0.0.0.0 isn't a big security issue in this case, as all
    # external traffic has to go through the host first.
    command: yarn start --host=0.0.0.0
    restart: always
    links:
      - api
      - tiles
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ANALYTICS_SERVER=${ANALYTICS_SERVER}
      - ANALYTICS_KEY=${ANALYTICS_KEY}
      - APISERVER=http://api:5555
      - TILESERVER=http://tiles:3001
    ports:
      - 3000:3000
