version: '3.2'

services:
  api:
    ports:
      - 5000:5000
    environment:
      - FLASK_SECRET=unsafedevsecret
      - JWT_SECRET=unsafejwtsecret
      - SQLALCHEMY_DATABASE_URI=sqlite:////tmp/accessmap-api.db
      - OAUTH_CACHE_DIR=/tmp/accessmap-api-cache
      - OSM_URI=https://master.apis.dev.openstreetmap.org/
      - CONSUMER_CALLBACK_URI=http://localhost:2015/login_callback
      - OSM_CLIENT_ID=$STAGING_OSM_CLIENT_ID
      - OSM_CLIENT_SECRET=$STAGING_OSM_CLIENT_SECRET

  router:
    ports:
      - 5656:5656
    environment:
      - SERVER_PORT=5656

  caddy:
    ports:
      - 2015:2015
    environment:
      - ANALYTICS_URL=host.docker.internal:9999
    entrypoint:
      # A hack for the non-existence of docker.host.internal as of docker version 18:
      # rakam is launched separately (as it can be used by multiple services and claims
      # a single host dir), and in development is on the host, so we need
      # docker.host.interal to exist
      - /bin/sh
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && /usr/bin/caddy --conf /etc/Caddyfile --log stdout
    volumes:
      - ./config/caddy/Caddyfile.tls.dev:/etc/Caddyfile.tls
