version: '3.2'

services:

  tippecanoe:
    entrypoint: sh /build_tiles.sh /home/tippecanoe/data https://${HOST}

  # TODO: use gunicorn to serve API
  api:
    restart: always
      - FLASK_SECRET=$FLASK_SECRET
      - JWT_SECRET=$JWT_SECRET
      - SQLALCHEMY_DATABASE_URI=$PRODUCTION_API_DATABASE_URI
      - OAUTH_CACHE_DIR="/tmp/accessmap-api-cache"
      - OSM_URI="https://api.openstreetmap.org/"
      - CONSUMER_CALLBACK_URI=$HOST/login_callback
      - OSM_CLIENT_ID=$OSM_CLIENT_ID
      - OSM_CLIENT_SECRET=$OSM_CLIENT_SECRET

  router:
    restart: always

  webapp:
    environment:
      - HOST=$HOST

  caddy:
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - ANALYTICS_URL=$ANALYTICS_URL
    volumes:
      - ./config/Caddyfile.tls.prod:/etc/Caddyfile.tls
      - /docker/.caddy:/root/.caddy
