version: '3.2'

services:

  api:
    restart: always

  webapp:
    restart: always
    environment:
      - OPENID_CLIENT_ID=AccessMap

  caddy:
    volumes:
      - ./config/Caddyfile.prod:/etc/Caddyfile
      - /docker/.caddy:/root/.caddy
    environment:
      - ANALYTICS_URL=${ANALYTICS_URL}
    ports:
      - 80:80
      - 443:443
