version: '3.2'

services:

  api:
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  caddy:
    volumes:
      - ./config/Caddyfile.staging:/etc/Caddyfile
      - /docker/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
