version: '3.8'

x-api-config: &api-config
  env_file: accessmap.env
  build:
    context: https://github.com/accessmap/accessmap-api.git#v0.1.2

x-unweaver-config: &unweaver-config
  env_file: accessmap.env
  build:
    context: https://github.com/nbolten/unweaver.git#f37ebb49c83b9818d1f83f907a4e1c8d361918bc
  stop_signal: SIGINT


services:
#
# primary services:
# `docker-compose up`.
#

  caddy:
    env_file: accessmap.env
    image: abiosoft/caddy:0.11.5-no-stats
    restart: unless-stopped
    volumes:
      - ./config/caddy/Caddyfile:/etc/Caddyfile
      - caddy-persist:/root/.caddy
      - ./build/tiles:/tiles:ro
      - ./build/webapp:/webapp
    links:
      - unweaver
      - api

  api:
    <<: *api-config
    command: poetry run gunicorn --bind 0.0.0.0:5000 'wsgi:build_app(endpoint="/api/v1")'
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

  unweaver:
    <<: *unweaver-config
    command: serve /build -h 0.0.0.0 -p 5656
    restart: unless-stopped
    volumes:
      - ./build/unweaver:/build:rw

#
# "migrate" steps - these run database migrations
# `docker-compose run migrate_api-db`
#
  migrate_api_db:
    <<: *api-config
    command: sh -c "poetry run flask db upgrade && poetry run flask db migrate"
    profiles:
      - migrate

#
# "build" steps - run these using the "build" profile to create the assets
# for AccessMap before running the other services.
# `docker-compose run build_unweaver && docker-compose run build_tiles && docker-compose run build_webapp`
#
  build_unweaver:
    <<: *unweaver-config
    entrypoint: bash -c "mkdir -p /build/layers && cp -r /config/* /build/ && cp /data/transportation.geojson /build/layers/ && unweaver build /build --changes-sign incline"
    stdin_open: true
    tty: true
    volumes:
      - ./config/unweaver:/config:ro
      - ./data:/data:ro
      - ./build/unweaver:/build:rw
    profiles:
      - build

  build_tiles:
    env_file: accessmap.env
    build: ./dockerfiles/tippecanoe
    entrypoint: "sh /build_tiles.sh /home/tippecanoe/input /home/tippecanoe/output"
    volumes:
      - ./config/tippecanoe/build_tiles.sh:/build_tiles.sh:ro
      - ./config/tippecanoe/pedestrian-tilejson.json:/home/tippecanoe/pedestrian.json:ro
      - ./config/tippecanoe/regions-tilejson.json:/home/tippecanoe/regions.json:ro
      - ./data/transportation.geojson:/home/tippecanoe/input/transportation.geojson:ro
      - ./data/regions.geojson:/home/tippecanoe/input/regions.geojson:ro
      - ./build/tiles:/home/tippecanoe/output:rw
    profiles:
      - build

  build_webapp:
    env_file: accessmap.env
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#v1.0.6
    command: npm run build
    volumes:
      - ./build/webapp:/www/public
      - ./data/regions.geojson:/www/regions.json:ro
    profiles:
      - build

volumes:
    caddy-persist:
