version: '3.2'

services:

  rakamdb:
    image: postgres:9.6.1

  rakam:
    build: ./builds/rakam
    depends_on:
      - rakamdb
    environment:
      - WAITFOR=rakamdb:5432

  fetch_and_tippecanoe:
    build: ./builds/tippecanoe-curl
    entrypoint: sh /fetch_and_build_tiles.sh /home/tippecanoe/data
    volumes:
      - ./scripts/fetch_and_build_tiles.sh:/fetch_and_build_tiles.sh
      - ${AM_DATADIR:-/docker/amdata}:/home/tippecanoe/data

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#feature/elevators
    command: gunicorn -b 0.0.0.0:5555 --access-logfile=- accessmapapi:app
    volumes:
      - ${AM_DATADIR:-/docker/amdata}:/www/data

  webapp:
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#feature/elevators
    command: yarn build
    volumes:
      - type: volume
        source: webapp-build
        target: /www/public
        volume:
          nocopy: true
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ANALYTICS_KEY=${ANALYTICS_KEY}

  caddy:
    image: abiosoft/caddy:0.10.10
    volumes:
      - type: volume
        source: webapp-build
        target: /webapp
      - ${AM_DATADIR:-/docker/amdata}:/amdata
    links:
      - api
      - rakam

volumes:
  webapp-build:
