version: '3.2'

services:
  api:
    build:
      context: ../../accessmap-api
    command: poetry run gunicorn --bind 0.0.0.0:5000 'wsgi:build_app(endpoint="/api/v1")'
    dns:
      - 8.8.8.8
      - 8.8.4.4

  router:
    build: ./dockerfiles/unweaver
    command: poetry run unweaver run /data -h 0.0.0.0 -p 5656
    volumes:
      - ./build/router:/data:ro

  caddy:
    image: abiosoft/caddy:0.11.5-no-stats
    volumes:
      - ./config/caddy/Caddyfile.shared:/etc/Caddyfile.shared
      - ./config/caddy/Caddyfile.tiles.shared:/etc/Caddyfile.tiles.shared
      - ./build/tiles:/tiles:ro
      - ./build/webapp:/webapp
    links:
      - router
      - api
