version: '3.2'

services:
  api:
    restart: always
    environment:
      - SECRET_KEY=$STAGING_API_SECRET
      - JWT_SECRET_KEY=$STAGING_JWT_SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=$STAGING_API_DATABASE_URI
      - OSM_URI=$STAGING_OSM_URI
      - CONSUMER_CALLBACK_URI=${STAGING_CONSUMER_CALLBACK_URI:-$STAGING_HOST/login_callback}
      - OSM_CLIENT_ID=$STAGING_OSM_CLIENT_ID
      - OSM_CLIENT_SECRET=$STAGING_OSM_CLIENT_SECRET

  router:
    restart: always

  caddy:
    restart: always
    volumes:
      - ./config/caddy/Caddyfile.tls.staging:/etc/Caddyfile.tls
      - /docker/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - ANALYTICS_URL=$STAGING_ANALYTICS_URL
      - HOST=${STAGING_HOST}
      - ACME_AGREE=true
