version: '3.2'

services:

  rakamdb:
    environment:
      - POSTGRES_USER=rakam
      - POSTGRES_PASSWORD=${RAKAMDB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 6666:5432
    volumes:
      - "${DB_VOLUME}:/var/lib/postgresql/data/pgdata"
    restart: always

  rakam:
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://rakam:${RAKAMDB_PASSWORD}@rakamdb:5432/rakam
      - RAKAM_CONFIG_LOCK__KEY=${RAKAM_CONFIG_LOCK__KEY}
    restart: always

  api:
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  webapp:
    restart: always
    environment:
      - OPENID_CLIENT_ID=AccessMap

  caddy:
    volumes:
      - ./config/Caddyfile.prod:/etc/Caddyfile
      - /docker/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
