version: '3.2'

services:

  tippecanoe:
    build: ./builds/tippecanoe
    volumes:
      - ./scripts/build_tiles.sh:/build_tiles.sh
      - ./config/tilejson/pedestrian.json:/home/tippecanoe/data/pedestrian.json
      - ${DATADIR:-/docker/am_bellingham}:/home/tippecanoe/data

  api_build:
    build:
      context: https://github.com/accessmap/accessmap-api.git#city/bellingham
    command: python build.py
    volumes:
      - ${DATADIR:-/docker/am_bellingham}:/www/data
      - ./config/layers.json:/www/layers.json

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#develop
    command: gunicorn -b 0.0.0.0:5656 --access-logfile=- accessmapapi.app:app
    volumes:
      - ${DATADIR:-/docker/am_bellingham}:/www/data
      - ./config/layers.json:/www/layers.json
      - ./config/costs_user.py:/www/cost_fun/costs_user.py

  webapp:
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#city/bellingham
    command: yarn build
    volumes:
      - type: volume
        source: webapp-build
        target: /www/public
        volume:
          nocopy: true
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ANALYTICS_KEY=${ANALYTICS_KEY}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}

  caddy:
    image: abiosoft/caddy:0.10.10
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - type: volume
        source: webapp-build
        target: /webapp
      - ${DATADIR:-/docker/am_bellingham}:/amdata
    links:
      - api

volumes:
  webapp-build:
