version: '3.2'

services:

  tippecanoe:
    entrypoint: sh /build_tiles.sh /home/tippecanoe/data uw.accessmap.io

  api:
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  caddy:
    volumes:
      - ./config/Caddyfile.prod:/etc/Caddyfile
      - /docker/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
