version: '3.2'

services:

  tippecanoe:
    build: ./builds/tippecanoe
    volumes:
      - ./scripts/build_tiles.sh:/build_tiles.sh
      - ./config/tilejson/paths.json:/home/tippecanoe/data/paths.json
      - ./config/tilejson/points.json:/home/tippecanoe/data/points.json
      - ${DATADIR:-/docker/accessmapuw_data}:/home/tippecanoe/data

  api_build:
    build:
      context: https://github.com/accessmap/accessmap-api.git#uw
    command: python build.py
    volumes:
      - ${DATADIR:-/docker/accessmapuw_data}:/www/data
      - ./config/layers.json:/www/layers.json

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#uw
    depends_on:
      - api_build
    command: gunicorn -b 0.0.0.0:5555 --access-logfile=- accessmapapi.app:app
    volumes:
      - ${DATADIR:-/docker/accessmapuw_data}:/www/data
      - ./config/layers.json:/www/layers.json

  webapp:
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#accessmapuw
    command: yarn build
    volumes:
      - type: volume
        source: webapp-build
        target: /www/public
        volume:
          nocopy: true
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ANALYTICS_KEY=${ANALYTICS_KEY}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}

  caddy:
    image: abiosoft/caddy:0.10.10
    volumes:
      - type: volume
        source: webapp-build
        target: /webapp
      - ${DATADIR:-/docker/accessmapuw_data}:/amdata
    links:
      - api

volumes:
  webapp-build:
