version: '3.2'

services:

  tippecanoe:
    build: ./builds/tippecanoe
    entrypoint: sh /build_tiles.sh /home/tippecanoe/data
    volumes:
      - ./scripts/build_tiles.sh:/build_tiles.sh
      - ./config/tilejson/paths.json:/home/tippecanoe/data/paths.json
      - ./config/tilejson/points.json:/home/tippecanoe/data/points.json
      - ${AM_DATADIR:-/docker/amuwdata}:/home/tippecanoe/data

  api_build:
    build:
      context: https://github.com/accessmap/accessmap-api.git#uw
    command: python build.py
    volumes:
      - ${AM_DATADIR:-/docker/amuwdata}:/www/data
      - ./config/layers.json:/www/layers.json

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#uw
    depends_on:
      - api_build
    command: gunicorn -b 0.0.0.0:5555 --access-logfile=- accessmapapi.app:app
    volumes:
      - ${AM_DATADIR:-/docker/amuwdata}:/www/data
      - ./config/layers.json:/www/layers.json

  caddy:
    image: abiosoft/caddy:0.10.10
    volumes:
      - ${AM_DATADIR:-/docker/amuwdata}:/amdata
    links:
      - api
