version: '3.2'

services:

  tippecanoe:
    entrypoint: sh /build_tiles.sh /home/tippecanoe/data https://${HOST}

  api:
    restart: always

  webapp:
    environment:
      - OPENID_CLIENT_ID=AccessMapUW
    restart: always

  caddy:
    ports:
      - 80:80
      - 443:443
    environment:
      - HOST=$HOST
      - ANALYTICS_URL=$ANALYTICS_URL
    volumes:
      - ./config/Caddyfile.tls.dev:/etc/Caddyfile.tls
      - /docker/.caddy:/root/.caddy
