version: '3.2'

services:

  tippecanoe:
    build: ./builds/tippecanoe
    volumes:
      - ./scripts/build_tiles.sh:/build_tiles.sh
      - ./config/tilejson/pedestrian.json:/home/tippecanoe/data/pedestrian.json
      - ./data/sidewalks.geojson:/home/tippecanoe/data/sidewalks.geojson:ro
      - ./data/crossings.geojson:/home/tippecanoe/data/crossings.geojson:ro
      - ./data/elevator_paths.geojson:/home/tippecanoe/data/elevator_paths.geojson:ro
      - type: volume
        source: tippecanoe
        target: /home/tippecanoe/data
        volume:
          nocopy: true

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#develop
    command: poetry run gunicorn --bind 0.0.0.0:5000 wsgi:app

  router_build:
    build: ./builds/unweaver
    command: poetry run unweaver build /data
    volumes:
      - ./config/unweaver:/data:rw
      - ./data:/data/layers:ro

  router:
    build: ./builds/unweaver
    depends_on:
      - router_build
    command: poetry run unweaver run /data -h 0.0.0.0 -p 5656
    volumes:
      - ./config/unweaver:/data:ro
      - ./data:/data/layers:ro

  webapp:
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#develop
    command: npm run build
    volumes:
      - type: volume
        source: webapp-build
        target: /www/public
        volume:
          nocopy: true
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ANALYTICS_KEY=${ANALYTICS_KEY}

  caddy:
    image: abiosoft/caddy:0.10.10
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - type: volume
        source: webapp-build
        target: /webapp
      - type: volume
        source: tippecanoe
        target: /tiles
    links:
      - router
      - api

volumes:
  webapp-build:
  tippecanoe:
