version: '3.2'

services:

  rakamdb:
    image: postgres:9.6.1

  rakam:
    build: ./rakam-waitfor
    environment:
      - WAITFOR=rakamdb:5432
    depends_on:
      - rakamdb

  api:
    build:
      context: https://github.com/accessmap/accessmap-api.git#develop
    command: python3 ./runserver.py

  tiles:
    build:
      context: https://github.com/accessmap/accessmap-vt.git
    command: yarn app 0.0.0.0
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DOCKER=no
    volumes:
      - ./config/tiles/sources.json:/www/sources.json

  webapp:
    build:
      context: https://github.com/accessmap/accessmap-webapp.git#develop
    command: yarn build
    # Note: binding 0.0.0.0 isn't a big security issue in this case, as all
    # external traffic has to go through the host first.
    volumes:
      - type: volume
        source: webapp-build
        target: /www/public
        volume:
          nocopy: true
    links:
      - api
      - tiles
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ANALYTICS_SERVER=http://rakam:9999
      - ANALYTICS_KEY=${ANALYTICS_KEY}
      - APISERVER=http://api:5555
      - TILESERVER=http://tiles:3001

  caddy:
    image: abiosoft/caddy:0.10.10
    volumes:
      - type: volume
        source: webapp-build
        target: /webapp
    links:
      - api
      - rakam
      - tiles
      - webapp

volumes:
  webapp-build:
