version: '3.2'

services:

  rakamdb:
    environment:
      - POSTGRES_USER=${RAKAMDB_USER}
      - POSTGRES_PASSWORD=${RAKAMDB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 6666:5432
    volumes:
      - "${DB_VOLUME}:/var/lib/postgresql/data/pgdata"
    restart: always

  rakam:
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://${RAKAMDB_USER}:${RAKAMDB_PASSWORD}@rakamdb:5432/rakam
      - RAKAM_CONFIG_LOCK__KEY=${RAKAM_CONFIG_LOCK__KEY}
    restart: always

  api:
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  tiles:
    restart: always

  webapp:
    command: yarn prod --host 0.0.0.0
    restart: always
    ports:
      - 3000:3000
