version: '3.2'

services:
  rakamdb:
    image: postgres:11.4
    environment:
      - POSTGRES_USER=rakam
      - POSTGRES_PASSWORD=dummy
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 6666:5432
    volumes:
      - rakamdb:/var/lib/postgresql/data/pgdata

  rakam:
    entrypoint: "bash -c 'while !</dev/tcp/rakamdb/5432; do sleep 1; done; java $JAVA_OPTS -cp /app/lib/*: -Denv=RAKAM_CONFIG org.rakam.ServiceStarter'"
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://rakam:dummy@rakamdb:5432/rakam
      - RAKAM_CONFIG_LOCK__KEY=mylockKey
    links:
      - rakamdb

volumes:
  rakamdb:
