version: '3.2'

services:
  rakamdb:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=rakam
      - POSTGRES_PASSWORD=dummy
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 6666:5432
    volumes:
      - "${DB_VOLUME:-/docker/rakamdb}:/var/lib/postgresql/data/pgdata"

  rakam:
    build: ./dockerfiles/rakam-waitfor
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=postgres://rakam:dummy@rakamdb:5432/rakam
      - RAKAM_CONFIG_LOCK__KEY=mylockKey
      - WAITFOR=rakamdb:5432
    links:
      - rakamdb
