version: '3.2'

services:

  rakam:
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=${RAKAM_PROD_DB_URL}
      - RAKAM_CONFIG_LOCK__KEY=${RAKAM_CONFIG_LOCK__KEY}
    restart: always
