version: '3.2'

services:
  rakam:
    env_file: rakam.env
    entrypoint: "bash -c 'java $JAVA_OPTS -cp /app/lib/*: -Denv=RAKAM_CONFIG org.rakam.ServiceStarter'"
    image: buremba/rakam@sha256:6cbeaf9429130d7e4987c4b5dd4566d24f0cb05e56a35c9507be3187a73002b8
    ports:
      - 9999:9999
    environment:
      - RAKAM_CONFIG_HTTP_SERVER_ADDRESS=0.0.0.0:9999
      - RAKAM_CONFIG_STORE_ADAPTER=postgresql
      - RAKAM_CONFIG_CUSTOM__DATA__SOURCE_ENABLED=true
      - RAKAM_CONFIG_EVENT__EXPLORER_ENABLED=true
      - RAKAM_CONFIG_MODULE_WEBSITE_MAPPER=true
      - RAKAM_CONFIG_MODULE_WEBSITE_MAPPER_USER-AGENT=true
      - RAKAM_CONFIG_MODULE_WEBSITE_MAPPER_REFERRER=true
      - RAKAM_CONFIG_PLUGIN_GEOIP_ENABLED=true
      - RAKAM_CONFIG_PLUGIN_GEOIP_DATABASE_URL=https://git.io/GeoLite2-City.mmdb
      - RAKAM_CONFIG_PLUGIN_USER_ENABLED=true
      - RAKAM_CONFIG_PLUGIN_USER_ENABLE__USER__MAPPING=true
      - RAKAM_CONFIG_PLUGIN_USER_STORAGE=postgresql
      - RAKAM_CONFIG_PLUGIN_USER_STORAGE_IDENTIFIER__COLUMN=id
      - RAKAM_CONFIG_USER_FUNNEL__ANALYSIS_ENABLED=true
      - RAKAM_CONFIG_USER_RETENTION__ANALYSIS_ENABLED=true
