version: '3.2'

services:
  rakam:
    build: ./dockerfiles/rakam
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=${PROD_RAKAM_DB_URL}
      - RAKAM_CONFIG_LOCK__KEY=${PROD_RAKAM_CONFIG_LOCK__KEY}
    restart: always
