version: '3.2'

services:
  rakam:
    ports:
      - 9999:9999
    environment:
      - RAKAM_CONFIG_MODULE_WEBSITE_MAPPER=true
      - RAKAM_CONFIG_MODULE_WEBSITE_MAPPER_USER-AGENT=true
      - RAKAM_CONFIG_MODULE_WEBSITE_MAPPER_REFERRER=true
      - RAKAM_CONFIG_PLUGIN_GEOIP_ENABLE=true
      - RAKAM_CONFIG_PLUGIN_USER_ENABLE=true
      - RAKAM_CONFIG_PLUGIN_USER_ENABLE_USER_MAPPING=true
