version: '3.2'

services:
  rakam:
    build: ./dockerfiles/rakam
    environment:
      - RAKAM_CONFIG_STORE_ADAPTER_POSTGRESQL_URL=${STAGING_RAKAM_DB_URL}
      - RAKAM_CONFIG_LOCK__KEY=${STAGING_RAKAM_CONFIG_LOCK__KEY}
    restart: always
    # TODO: figure out if there's a way to do 'wait-for' a connection to the db a la
    # local dev solution
